### ISSUE TITLE
Plugin insert itself twice in the network parameter screen

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-WakeOnLan#2]
When installing the plugin on OpenPLi 6.2 we have twice in the network configuration menu.
1st one is working, 2nd one doesn't perform any action.

See picture: look for "Send Wake-on-LAN"

<img width="186" alt="capture d ecran 2018-09-15 a 14 23 06" src="https://user-images.githubusercontent.com/13857365/45586205-f4980500-b8f2-11e8-8a84-832d4c61f668.png">

**Comment by arn354** [comment]
actually - first entry is to configure, 2nd to send a wol paket. First one was not correctly labeled
